/// Localization and currency formatting.
///
/// Swahili is the default and English the fallback, not the other way round.
/// That ordering shows up in the lookup chain below and in `supportedLocales`.
///
/// Currency notes for TZS:
///  * No circulating subunit. Never show "TSh 3,450.00" — it reads as broken.
///  * Thousands separator is a comma, and the symbol precedes the amount:
///    "TSh 3,450".
///  * Fares are stored in cents internally and divided out only at the edge.

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';

import '../models/vehicle_category.dart';

// =====================================================================
// Currency
// =====================================================================

final NumberFormat _tzsFormat = NumberFormat.decimalPattern('sw_TZ');

/// "TSh 3,450"
String formatTzs(int cents) {
  final shillings = (cents / 100).round();
  return 'TSh ${_tzsFormat.format(shillings)}';
}

/// Compact form for tight spaces like the category carousel: "3.4K".
/// Below 10,000 TZS the full number still fits and is clearer.
String formatTzsCompact(int cents) {
  final shillings = (cents / 100).round();
  if (shillings < 10000) return _tzsFormat.format(shillings);
  return '${(shillings / 1000).toStringAsFixed(1)}K';
}

/// Parses user-typed amounts tolerantly: "3,450", "3450", "TSh 3450".
int? parseTzsToCents(String input) {
  final cleaned = input.replaceAll(RegExp(r'[^0-9]'), '');
  if (cleaned.isEmpty) return null;
  return int.parse(cleaned) * 100;
}

// =====================================================================
// Localization
// =====================================================================

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const supportedLocales = [
    Locale('sw', 'TZ'), // default
    Locale('en', 'TZ'),
  ];

  Map<String, String> get _strings =>
      _translations[locale.languageCode] ?? _translations['sw']!;

  /// Looks up a key, substituting {placeholders}. Falls back through
  /// Swahili, then English, then the raw key — a missing translation should
  /// degrade to something legible, never to a blank widget.
  String translate(String key, {Map<String, String>? params}) {
    var value = _strings[key] ??
        _translations['sw']![key] ??
        _translations['en']![key] ??
        key;

    if (params != null) {
      params.forEach((k, v) => value = value.replaceAll('{$k}', v));
    }
    return value;
  }

  String categoryName(VehicleCategory category) =>
      translate('category.${category.name}');

  /// Swahili pluralisation is regular enough for these cases that a full
  /// ICU plural rule set would be overkill, but minutes still need it.
  String minutes(int n) => translate(n == 1 ? 'time.minute_one' : 'time.minute_other',
      params: {'n': '$n'});
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['sw', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// ---------------------------------------------------------------------
// Strings
//
// Kept inline here for a self-contained scaffold. In the real project these
// move to ARB files under lib/l10n/ and are generated by gen_l10n so the
// Swahili copy can be reviewed by a translator without touching Dart.
// ---------------------------------------------------------------------

const Map<String, Map<String, String>> _translations = {
  'sw': {
    // Rider
    'rider.where_to': 'Unaenda wapi?',
    'rider.pickup_here': 'Nikuchukue hapa',
    'rider.estimated_fare': 'Makadirio ya nauli',
    'rider.request_ride': 'Omba {category}',
    'rider.eta_min': 'dakika {min}',
    'rider.surge_active': 'Mahitaji juu ×{x}',
    'rider.searching': 'Tunatafuta dereva...',
    'rider.no_drivers': 'Hakuna dereva karibu. Jaribu tena baada ya dakika chache.',
    'rider.driver_arriving': 'Dereva anakuja',
    'rider.trip_started': 'Safari imeanza',

    // Categories
    'category.boda': 'Bodaboda',
    'category.bajaji': 'Bajaji',
    'category.standard': 'Gari',
    'category.xl': 'Gari Kubwa',
    'category.express': 'Express',

    // Driver
    'driver.new_request': 'Ombi jipya la safari',
    'driver.accept': 'Kubali',
    'driver.decline': 'Kataa',
    'driver.pickup': 'Mahali pa kuchukua',
    'driver.dropoff': 'Mahali pa kushusha',
    'driver.away': 'umbali {d}',
    'driver.eta_min': 'dakika {min}',
    'driver.to_pickup': 'hadi kwa abiria',
    'driver.rider_rating': 'kiwango',
    'driver.payment': 'malipo',
    'driver.surge_bonus': 'Bonasi ya mahitaji ×{x}',
    'driver.offer_taken': 'Safari imeshachukuliwa na dereva mwingine.',
    'driver.go_online': 'Anza kazi',
    'driver.go_offline': 'Maliza kazi',

    // Payment
    'payment.cash': 'Taslimu',
    'payment.mobile_money': 'Simu',
    'payment.card': 'Kadi',
    'payment.wallet': 'Pochi',
    'payment.prompt_sent': 'Angalia simu yako na uweke PIN yako.',
    'payment.confirming': 'Tunathibitisha malipo yako...',
    'payment.success': 'Malipo yamekamilika',
    'payment.failed': 'Malipo hayakufanikiwa. Jaribu tena.',
    'payment.select_network': 'Chagua mtandao wako',

    // Errors
    'error.network': 'Hakuna mtandao. Tunajaribu tena...',
    'error.location_denied': 'Tunahitaji ruhusa ya eneo ili kukutafutia dereva.',
    'error.gps_off': 'Washa GPS ili kuendelea.',
    'error.quote_expired': 'Bei imeisha muda. Tunapata bei mpya.',

    // Time
    'time.minute_one': 'dakika {n}',
    'time.minute_other': 'dakika {n}',
  },
  'en': {
    'rider.where_to': 'Where to?',
    'rider.pickup_here': 'Pick me up here',
    'rider.estimated_fare': 'Estimated fare',
    'rider.request_ride': 'Request {category}',
    'rider.eta_min': '{min} min',
    'rider.surge_active': 'High demand ×{x}',
    'rider.searching': 'Finding a driver...',
    'rider.no_drivers': 'No drivers nearby. Try again in a few minutes.',
    'rider.driver_arriving': 'Driver on the way',
    'rider.trip_started': 'Trip started',

    'category.boda': 'Bodaboda',
    'category.bajaji': 'Bajaji',
    'category.standard': 'Car',
    'category.xl': 'Car XL',
    'category.express': 'Express',

    'driver.new_request': 'New ride request',
    'driver.accept': 'Accept',
    'driver.decline': 'Decline',
    'driver.pickup': 'Pickup',
    'driver.dropoff': 'Dropoff',
    'driver.away': '{d} away',
    'driver.eta_min': '{min} min',
    'driver.to_pickup': 'to pickup',
    'driver.rider_rating': 'rating',
    'driver.payment': 'payment',
    'driver.surge_bonus': 'Demand bonus ×{x}',
    'driver.offer_taken': 'Another driver took this ride.',
    'driver.go_online': 'Go online',
    'driver.go_offline': 'Go offline',

    'payment.cash': 'Cash',
    'payment.mobile_money': 'Mobile',
    'payment.card': 'Card',
    'payment.wallet': 'Wallet',
    'payment.prompt_sent': 'Check your phone and enter your PIN.',
    'payment.confirming': 'Confirming your payment...',
    'payment.success': 'Payment complete',
    'payment.failed': 'Payment did not go through. Try again.',
    'payment.select_network': 'Choose your network',

    'error.network': 'No connection. Retrying...',
    'error.location_denied': 'Location permission is needed to find you a driver.',
    'error.gps_off': 'Turn on GPS to continue.',
    'error.quote_expired': 'That price expired. Getting a new one.',

    'time.minute_one': '{n} minute',
    'time.minute_other': '{n} minutes',
  },
};
