/// Localization — Swahili, English, French.
///
/// Swahili is the default and the fallback, not English. A missing French
/// string falls through to Swahili before English, because a Swahili speaker
/// seeing one untranslated label is a smaller failure than a francophone
/// seeing a mix of two foreign languages.
///
/// French earns its place here: Tanzania borders Burundi, Rwanda and the DRC,
/// there are established Congolese and Burundian communities in Dar and
/// Kigoma, and francophone tourists are a real share of airport and Zanzibar
/// ferry pickups. It is not decoration.
///
/// Currency notes for TZS:
///  * No circulating subunit. Never render "TSh 3,450.00" — it reads broken.
///  * Symbol precedes the amount, comma thousands separator: "TSh 3,450".
///  * French convention would use a space separator, but TZS amounts are
///    written the same way in all three languages in Tanzania, so the number
///    format does not switch with locale. Only the words around it do.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import '../format/tzs.dart';
import '../models/models.dart';

// Currency helpers live in core/format/tzs.dart; re-exported so screens can
// import either path without a duplicate-symbol conflict.
export '../format/tzs.dart';

// =====================================================================
// Supported languages
// =====================================================================

enum AppLanguage {
  swahili('sw', 'Kiswahili', 'SW'),
  english('en', 'English', 'EN'),
  french('fr', 'Français', 'FR');

  const AppLanguage(this.code, this.label, this.short);

  /// ISO 639-1 code, stored in `users.preferred_language`.
  final String code;

  /// Endonym — each language named in itself. A francophone scanning the
  /// list should find "Français", not "French".
  final String label;

  /// Two-letter badge for the compact switcher.
  final String short;

  static AppLanguage fromCode(String? code) => AppLanguage.values.firstWhere(
        (l) => l.code == code,
        orElse: () => AppLanguage.swahili,
      );

  Locale get locale => Locale(code, 'TZ');
}

// =====================================================================
// Localization
// =====================================================================

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static List<Locale> get supportedLocales =>
      AppLanguage.values.map((l) => l.locale).toList();

  AppLanguage get language => AppLanguage.fromCode(locale.languageCode);

  Map<String, String> get _strings =>
      _translations[locale.languageCode] ?? _translations['sw']!;

  /// Looks up a key, substituting {placeholders}. Falls back through the
  /// active language, then Swahili, then English, then the raw key — a
  /// missing translation degrades to something legible, never to a blank.
  String translate(String key, {Map<String, String>? params}) {
    var value = _strings[key] ??
        _translations['sw']![key] ??
        _translations['en']![key] ??
        key;
    params?.forEach((k, v) => value = value.replaceAll('{$k}', v));
    return value;
  }

  String categoryName(VehicleCategory category) =>
      translate('category.${category.wire}');

  String minutes(int n) => translate(
      n == 1 ? 'time.minute_one' : 'time.minute_other',
      params: {'n': '$n'});
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLanguage.values.any((l) => l.code == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// ---------------------------------------------------------------------
// Strings
//
// Inline here so the scaffold stays self-contained. In the real project these
// move to ARB files under lib/l10n/ generated by gen_l10n, so a translator can
// work on the Swahili and French copy without touching Dart.
// ---------------------------------------------------------------------

const Map<String, Map<String, String>> _translations = {
  // -------------------------------------------------------------------
  'sw': {
    'rider.where_to': 'Unaenda wapi?',
    'rider.pickup_here': 'Nikuchukue hapa',
    'rider.estimated_fare': 'Makadirio ya nauli',
    'rider.request_ride': 'Omba {category}',
    'rider.eta_min': 'dakika {min}',
    'rider.surge_active': 'Mahitaji juu ×{x}',
    'rider.searching': 'Tunatafuta dereva...',
    'rider.no_drivers': 'Hakuna dereva karibu. Jaribu tena baada ya dakika chache.',
    'rider.driver_arriving': 'Dereva anakuja',
    'rider.trip_started': 'Safari imeanza',

    'category.boda': 'Bodaboda',
    'category.bajaji': 'Bajaji',
    'category.standard': 'Gari',
    'category.xl': 'Gari Kubwa',
    'category.express': 'Express',

    'driver.new_request': 'Ombi jipya la safari',
    'driver.accept': 'Kubali',
    'driver.decline': 'Kataa',
    'driver.pickup': 'Mahali pa kuchukua',
    'driver.dropoff': 'Mahali pa kushusha',
    'driver.away': 'umbali {d}',
    'driver.eta_min': 'dakika {min}',
    'driver.to_pickup': 'hadi kwa abiria',
    'driver.rider_rating': 'kiwango',
    'driver.payment': 'malipo',
    'driver.surge_bonus': 'Bonasi ya mahitaji ×{x}',
    'driver.offer_taken': 'Safari imeshachukuliwa na dereva mwingine.',
    'driver.you_earn': 'Unapata',
    'driver.go_online': 'Anza kazi',
    'driver.go_offline': 'Maliza kazi',

    'payment.cash': 'Taslimu',
    'payment.mobile_money': 'Simu',
    'payment.card': 'Kadi',
    'payment.wallet': 'Pochi',
    'payment.prompt_sent': 'Angalia simu yako na uweke PIN yako.',
    'payment.confirming': 'Tunathibitisha malipo yako...',
    'payment.success': 'Malipo yamekamilika',
    'payment.failed': 'Malipo hayakufanikiwa. Jaribu tena.',
    'payment.select_network': 'Chagua mtandao wako',

    'settings.language': 'Lugha',
    'settings.choose_language': 'Chagua lugha',
    'settings.language_changed': 'Lugha imebadilishwa',

    'error.network': 'Hakuna mtandao. Tunajaribu tena...',
    'error.location_denied': 'Tunahitaji ruhusa ya eneo ili kukutafutia dereva.',
    'error.gps_off': 'Washa GPS ili kuendelea.',
    'error.quote_expired': 'Bei imeisha muda. Tunapata bei mpya.',

    'auth.phone_label': 'Namba ya simu',
    'auth.phone_hint': 'Tutakutumia msimbo wa tarakimu sita kwa SMS.',
    'auth.send_code': 'Tuma msimbo',
    'auth.code_label': 'Weka msimbo',
    'auth.verify': 'Thibitisha',
    'auth.change_number': 'Badilisha namba',
    'error.phone_format': 'Tumia muundo +255XXXXXXXXX',
    'error.otp_cooldown': 'Msimbo tayari umetumwa. Subiri sekunde {n}.',
    'error.otp_invalid': 'Msimbo si sahihi. Jaribu tena.',
    'status.searching': 'Tunatafuta dereva...',
    'status.accepted': 'Dereva anakuja',
    'status.arrived': 'Dereva amefika',
    'status.inProgress': 'Safari inaendelea',
    'status.completed': 'Safari imekamilika',
    'status.cancelled': 'Safari imesitishwa',
    'status.expired': 'Hakuna dereva karibu',
    'rider.confirm': 'Thibitisha safari',
    'rider.cancel': 'Sitisha safari',
    'rider.pay_now': 'Lipa sasa',
    'driver.online': 'Uko kazini',
    'driver.offline': 'Hauko kazini',
    'driver.today': 'Leo',
    'driver.trips': 'safari',
    'driver.earnings': 'mapato',
    'driver.arrived_btn': 'Nimefika',
    'driver.start_btn': 'Anza safari',
    'driver.complete_btn': 'Maliza safari',
    'driver.cash_collected': 'Nimepokea pesa',
    'driver.debt_warning': 'Deni la kamisheni: {amount}. Lipa ili uendelee kupokea safari.',
    'common.retry': 'Jaribu tena',
    'common.close': 'Funga',
    'nav.home': 'Nyumbani',
    'nav.activity': 'Safari zangu',
    'nav.account': 'Akaunti',
    'activity.empty': 'Bado hujafanya safari yoyote.',
    'account.sign_out': 'Toka',
    'account.commission_owed': 'Deni la kamisheni',
    'account.commission_limit': 'Kikomo: {amount}',
    'auth.name_title': 'Jina lako ni nani?',
    'auth.name_hint': 'Dereva ataliona jina hili anapokuja kukuchukua.',
    'auth.name_placeholder': 'Jina kamili',
    'auth.name_continue': 'Endelea',
    'error.name_too_short': 'Andika jina lako kamili.',
    'rating.title_driver': 'Mpe {name} nyota',
    'rating.title_rider': 'Mpe {name} nyota',
    'rating.1': 'Mbaya sana',
    'rating.2': 'Si nzuri',
    'rating.3': 'Wastani',
    'rating.4': 'Nzuri',
    'rating.5': 'Bora kabisa',
    'rating.submit': 'Tuma',
    'rating.skip': 'Rukia',
    'rider.fare_approx': 'Bei ya makadirio — njia kamili haipatikani sasa.',
    'account.edit_name': 'Badilisha jina',
    'account.save': 'Hifadhi',
    'sos.label': 'Dharura',
    'sos.hold': 'Shikilia kutuma ombi la dharura',
    'sos.keep_holding': 'Endelea kushikilia...',
    'sos.sending': 'Inatuma...',
    'sos.sent_title': 'Ombi la dharura limetumwa',
    'sos.sent_body': 'Tumepokea eneo lako. Timu yetu inawasiliana nawe, na mtu wako wa dharura amejulishwa.',
    'sos.sent_no_location': 'Tumepokea ombi lako lakini eneo halikupatikana. Tutakupigia — eleza ulipo.',
    'sos.call': 'Piga {n}',
    'sos.contact_title': 'Mtu wa dharura',
    'sos.contact_hint': 'Tutamtumia ujumbe ukiwa kwenye dharura.',
    'sos.contact_name': 'Jina',
    'sos.contact_phone': 'Namba ya simu',
    'sos.contact_save': 'Hifadhi',
    'sos.contact_none': 'Hujaweka bado',
    'photo.camera': 'Piga picha',
    'photo.gallery': 'Chagua kwenye ghala',
    'photo.change': 'Badilisha picha',
    'sos.err_name': 'Andika jina la mtu wa dharura.',
    'sos.err_phone': 'Tumia muundo wa kimataifa, mfano +255XXXXXXXXX.',
    'sos.contact_channels': 'Tutamtumia WhatsApp na SMS yenye eneo lako kamili.',
    'service.ride': 'Safari',
    'service.parcel': 'Kifurushi',
    'service.food': 'Chakula',
    'delivery.recipient': 'Anayepokea',
    'delivery.recipient_name': 'Jina lake',
    'delivery.recipient_phone': 'Namba yake ya simu',
    'delivery.what': 'Unatuma nini?',
    'delivery.what_hint': 'Mfano: nyaraka, dawa, chakula cha mchana',
    'delivery.size': 'Ukubwa',
    'delivery.size_small': 'Kidogo',
    'delivery.size_medium': 'Wastani',
    'delivery.size_large': 'Kubwa',
    'delivery.note': 'Maelezo ya ziada (hiari)',
    'delivery.cash': 'Pesa za kukusanya (hiari)',
    'delivery.cash_hint': 'Dereva atapokea pesa hizi kwa anayepokea.',
    'delivery.code': 'Msimbo wa kukabidhi',
    'delivery.code_hint': 'Mpe anayepokea msimbo huu. Dereva ataomba kabla ya kukabidhi.',
    'delivery.collected': 'Nimechukua kifurushi',
    'delivery.confirm': 'Kabidhi kifurushi',
    'delivery.enter_code': 'Weka msimbo wa anayepokea',
    'delivery.received_by': 'Amepokea nani? (hiari)',
    'delivery.wrong_code': 'Msimbo si sahihi.',
    'delivery.delivered': 'Kifurushi kimekabidhiwa',
    'delivery.no_insurance': 'Kwema haitoi bima ya vitu vinavyotumwa.',
    'delivery.err_name': 'Andika jina la anayepokea.',
    'delivery.err_what': 'Eleza unachotuma.',
    'delivery.failed_title': 'Sikuweza kukabidhi',
    'category.e_boda': 'Bodaboda ya Umeme',
    'category.e_bajaji': 'Bajaji ya Umeme',
    'category.e_car': 'Gari la Umeme',
    'category.electric': 'Umeme',
    'time.minute_one': 'dakika {n}',
    'time.minute_other': 'dakika {n}',
  },

  // -------------------------------------------------------------------
  'en': {
    'rider.where_to': 'Where to?',
    'rider.pickup_here': 'Pick me up here',
    'rider.estimated_fare': 'Estimated fare',
    'rider.request_ride': 'Request {category}',
    'rider.eta_min': '{min} min',
    'rider.surge_active': 'High demand ×{x}',
    'rider.searching': 'Finding a driver...',
    'rider.no_drivers': 'No drivers nearby. Try again in a few minutes.',
    'rider.driver_arriving': 'Driver on the way',
    'rider.trip_started': 'Trip started',

    'category.boda': 'Bodaboda',
    'category.bajaji': 'Bajaji',
    'category.standard': 'Car',
    'category.xl': 'Car XL',
    'category.express': 'Express',

    'driver.new_request': 'New ride request',
    'driver.accept': 'Accept',
    'driver.decline': 'Decline',
    'driver.pickup': 'Pickup',
    'driver.dropoff': 'Dropoff',
    'driver.away': '{d} away',
    'driver.eta_min': '{min} min',
    'driver.to_pickup': 'to pickup',
    'driver.rider_rating': 'rating',
    'driver.payment': 'payment',
    'driver.surge_bonus': 'Demand bonus ×{x}',
    'driver.offer_taken': 'Another driver took this ride.',
    'driver.you_earn': 'You earn',
    'driver.go_online': 'Go online',
    'driver.go_offline': 'Go offline',

    'payment.cash': 'Cash',
    'payment.mobile_money': 'Mobile',
    'payment.card': 'Card',
    'payment.wallet': 'Wallet',
    'payment.prompt_sent': 'Check your phone and enter your PIN.',
    'payment.confirming': 'Confirming your payment...',
    'payment.success': 'Payment complete',
    'payment.failed': 'Payment did not go through. Try again.',
    'payment.select_network': 'Choose your network',

    'settings.language': 'Language',
    'settings.choose_language': 'Choose language',
    'settings.language_changed': 'Language changed',

    'error.network': 'No connection. Retrying...',
    'error.location_denied': 'Location permission is needed to find you a driver.',
    'error.gps_off': 'Turn on GPS to continue.',
    'error.quote_expired': 'That price expired. Getting a new one.',

    'auth.phone_label': 'Phone number',
    'auth.phone_hint': 'We will send a six-digit code by SMS.',
    'auth.send_code': 'Send code',
    'auth.code_label': 'Enter the code',
    'auth.verify': 'Verify',
    'auth.change_number': 'Change number',
    'error.phone_format': 'Use the format +255XXXXXXXXX',
    'error.otp_cooldown': 'A code was already sent. Wait {n} seconds.',
    'error.otp_invalid': 'That code is not correct. Try again.',
    'status.searching': 'Finding a driver...',
    'status.accepted': 'Driver on the way',
    'status.arrived': 'Driver has arrived',
    'status.inProgress': 'Trip in progress',
    'status.completed': 'Trip complete',
    'status.cancelled': 'Trip cancelled',
    'status.expired': 'No drivers nearby',
    'rider.confirm': 'Confirm ride',
    'rider.cancel': 'Cancel ride',
    'rider.pay_now': 'Pay now',
    'driver.online': 'Online',
    'driver.offline': 'Offline',
    'driver.today': 'Today',
    'driver.trips': 'trips',
    'driver.earnings': 'earned',
    'driver.arrived_btn': 'I have arrived',
    'driver.start_btn': 'Start trip',
    'driver.complete_btn': 'Complete trip',
    'driver.cash_collected': 'Cash received',
    'driver.debt_warning': 'Commission owed: {amount}. Settle to keep receiving rides.',
    'common.retry': 'Try again',
    'common.close': 'Close',
    'nav.home': 'Home',
    'nav.activity': 'Activity',
    'nav.account': 'Account',
    'activity.empty': 'You have not taken any trips yet.',
    'account.sign_out': 'Sign out',
    'account.commission_owed': 'Commission owed',
    'account.commission_limit': 'Limit: {amount}',
    'auth.name_title': "What's your name?",
    'auth.name_hint': 'Your driver will see this name when picking you up.',
    'auth.name_placeholder': 'Full name',
    'auth.name_continue': 'Continue',
    'error.name_too_short': 'Please enter your full name.',
    'rating.title_driver': 'Rate {name}',
    'rating.title_rider': 'Rate {name}',
    'rating.1': 'Very poor',
    'rating.2': 'Poor',
    'rating.3': 'Okay',
    'rating.4': 'Good',
    'rating.5': 'Excellent',
    'rating.submit': 'Submit',
    'rating.skip': 'Skip',
    'rider.fare_approx': 'Approximate price — exact route unavailable.',
    'account.edit_name': 'Edit name',
    'account.save': 'Save',
    'sos.label': 'Emergency',
    'sos.hold': 'Hold to send an emergency alert',
    'sos.keep_holding': 'Keep holding...',
    'sos.sending': 'Sending...',
    'sos.sent_title': 'Emergency alert sent',
    'sos.sent_body': 'We have your location. Our team is contacting you, and your emergency contact has been notified.',
    'sos.sent_no_location': 'Alert sent, but your location was unavailable. We will call — describe where you are.',
    'sos.call': 'Call {n}',
    'sos.contact_title': 'Emergency contact',
    'sos.contact_hint': 'We text this person if you raise an alert.',
    'sos.contact_name': 'Name',
    'sos.contact_phone': 'Phone number',
    'sos.contact_save': 'Save',
    'sos.contact_none': 'Not set yet',
    'photo.camera': 'Take a photo',
    'photo.gallery': 'Choose from gallery',
    'photo.change': 'Change photo',
    'sos.err_name': 'Enter your emergency contact’s name.',
    'sos.err_phone': 'Use international format, e.g. +255XXXXXXXXX.',
    'sos.contact_channels': 'We send them WhatsApp and SMS with your exact location.',
    'service.ride': 'Ride',
    'service.parcel': 'Parcel',
    'service.food': 'Food',
    'delivery.recipient': 'Recipient',
    'delivery.recipient_name': 'Their name',
    'delivery.recipient_phone': 'Their phone number',
    'delivery.what': 'What are you sending?',
    'delivery.what_hint': 'For example: documents, medicine, lunch',
    'delivery.size': 'Size',
    'delivery.size_small': 'Small',
    'delivery.size_medium': 'Medium',
    'delivery.size_large': 'Large',
    'delivery.note': 'Extra instructions (optional)',
    'delivery.cash': 'Cash to collect (optional)',
    'delivery.cash_hint': 'The courier collects this from the recipient for you.',
    'delivery.code': 'Handover code',
    'delivery.code_hint': 'Give this to the recipient. The courier asks for it before handing over.',
    'delivery.collected': 'I have collected it',
    'delivery.confirm': 'Hand over',
    'delivery.enter_code': 'Enter the recipient’s code',
    'delivery.received_by': 'Received by (optional)',
    'delivery.wrong_code': 'That code does not match.',
    'delivery.delivered': 'Delivered',
    'delivery.no_insurance': 'Kwema does not insure items sent.',
    'delivery.err_name': 'Enter the recipient’s name.',
    'delivery.err_what': 'Describe what you are sending.',
    'delivery.failed_title': 'Could not deliver',
    'category.e_boda': 'Electric Bodaboda',
    'category.e_bajaji': 'Electric Bajaji',
    'category.e_car': 'Electric Car',
    'category.electric': 'Electric',
    'time.minute_one': '{n} minute',
    'time.minute_other': '{n} minutes',
  },

  // -------------------------------------------------------------------
  // Vehicle tier names stay in their local form. A francophone in Dar asks
  // for a "bajaji", not a "tuk-tuk" — translating the fleet vocabulary would
  // make the app harder to use, not easier.
  'fr': {
    'rider.where_to': 'Où allez-vous ?',
    'rider.pickup_here': 'Prenez-moi ici',
    'rider.estimated_fare': 'Tarif estimé',
    'rider.request_ride': 'Demander {category}',
    'rider.eta_min': '{min} min',
    'rider.surge_active': 'Forte demande ×{x}',
    'rider.searching': 'Recherche d\'un chauffeur...',
    'rider.no_drivers':
        'Aucun chauffeur à proximité. Réessayez dans quelques minutes.',
    'rider.driver_arriving': 'Le chauffeur arrive',
    'rider.trip_started': 'Trajet commencé',

    'category.boda': 'Bodaboda',
    'category.bajaji': 'Bajaji',
    'category.standard': 'Voiture',
    'category.xl': 'Voiture XL',
    'category.express': 'Express',

    'driver.new_request': 'Nouvelle demande de course',
    'driver.accept': 'Accepter',
    'driver.decline': 'Refuser',
    'driver.pickup': 'Prise en charge',
    'driver.dropoff': 'Destination',
    'driver.away': 'à {d}',
    'driver.eta_min': '{min} min',
    'driver.to_pickup': 'jusqu\'au client',
    'driver.rider_rating': 'note',
    'driver.payment': 'paiement',
    'driver.surge_bonus': 'Prime de demande ×{x}',
    'driver.offer_taken': 'Un autre chauffeur a pris cette course.',
    'driver.you_earn': 'Vous gagnez',
    'driver.go_online': 'Se mettre en ligne',
    'driver.go_offline': 'Se déconnecter',

    'payment.cash': 'Espèces',
    'payment.mobile_money': 'Mobile',
    'payment.card': 'Carte',
    'payment.wallet': 'Portefeuille',
    'payment.prompt_sent': 'Vérifiez votre téléphone et saisissez votre code PIN.',
    'payment.confirming': 'Confirmation de votre paiement...',
    'payment.success': 'Paiement effectué',
    'payment.failed': 'Le paiement a échoué. Réessayez.',
    'payment.select_network': 'Choisissez votre opérateur',

    'settings.language': 'Langue',
    'settings.choose_language': 'Choisir la langue',
    'settings.language_changed': 'Langue modifiée',

    'error.network': 'Pas de connexion. Nouvelle tentative...',
    'error.location_denied':
        'L\'accès à la position est nécessaire pour trouver un chauffeur.',
    'error.gps_off': 'Activez le GPS pour continuer.',
    'error.quote_expired': 'Ce tarif a expiré. Nouveau calcul en cours.',

    'auth.phone_label': 'Numéro de téléphone',
    'auth.phone_hint': 'Nous enverrons un code à six chiffres par SMS.',
    'auth.send_code': 'Envoyer le code',
    'auth.code_label': 'Saisissez le code',
    'auth.verify': 'Vérifier',
    'auth.change_number': 'Changer de numéro',
    'error.phone_format': 'Utilisez le format +255XXXXXXXXX',
    'error.otp_cooldown': 'Un code a déjà été envoyé. Attendez {n} secondes.',
    'error.otp_invalid': 'Code incorrect. Réessayez.',
    'status.searching': "Recherche d'un chauffeur...",
    'status.accepted': 'Le chauffeur arrive',
    'status.arrived': 'Le chauffeur est arrivé',
    'status.inProgress': 'Trajet en cours',
    'status.completed': 'Trajet terminé',
    'status.cancelled': 'Trajet annulé',
    'status.expired': 'Aucun chauffeur à proximité',
    'rider.confirm': 'Confirmer la course',
    'rider.cancel': 'Annuler la course',
    'rider.pay_now': 'Payer maintenant',
    'driver.online': 'En ligne',
    'driver.offline': 'Hors ligne',
    'driver.today': "Aujourd'hui",
    'driver.trips': 'courses',
    'driver.earnings': 'gagné',
    'driver.arrived_btn': 'Je suis arrivé',
    'driver.start_btn': 'Démarrer',
    'driver.complete_btn': 'Terminer',
    'driver.cash_collected': 'Espèces reçues',
    'driver.debt_warning': 'Commission due : {amount}. Réglez pour continuer.',
    'common.retry': 'Réessayer',
    'common.close': 'Fermer',
    'nav.home': 'Accueil',
    'nav.activity': 'Activité',
    'nav.account': 'Compte',
    'activity.empty': "Vous n'avez encore effectué aucun trajet.",
    'account.sign_out': 'Se déconnecter',
    'account.commission_owed': 'Commission due',
    'account.commission_limit': 'Plafond : {amount}',
    'auth.name_title': 'Comment vous appelez-vous ?',
    'auth.name_hint': 'Votre chauffeur verra ce nom en venant vous chercher.',
    'auth.name_placeholder': 'Nom complet',
    'auth.name_continue': 'Continuer',
    'error.name_too_short': 'Veuillez saisir votre nom complet.',
    'rating.title_driver': 'Notez {name}',
    'rating.title_rider': 'Notez {name}',
    'rating.1': 'Très mauvais',
    'rating.2': 'Mauvais',
    'rating.3': 'Correct',
    'rating.4': 'Bien',
    'rating.5': 'Excellent',
    'rating.submit': 'Envoyer',
    'rating.skip': 'Passer',
    'rider.fare_approx': 'Prix approximatif — itinéraire exact indisponible.',
    'account.edit_name': 'Modifier le nom',
    'account.save': 'Enregistrer',
    'sos.label': 'Urgence',
    'sos.hold': 'Maintenez pour envoyer une alerte',
    'sos.keep_holding': 'Continuez à maintenir...',
    'sos.sending': 'Envoi...',
    'sos.sent_title': 'Alerte d’urgence envoyée',
    'sos.sent_body': 'Nous avons votre position. Notre équipe vous contacte et votre contact d’urgence a été prévenu.',
    'sos.sent_no_location': 'Alerte envoyée, mais votre position est indisponible. Nous vous appellerons — décrivez où vous êtes.',
    'sos.call': 'Appeler le {n}',
    'sos.contact_title': 'Contact d’urgence',
    'sos.contact_hint': 'Nous prévenons cette personne si vous déclenchez une alerte.',
    'sos.contact_name': 'Nom',
    'sos.contact_phone': 'Numéro de téléphone',
    'sos.contact_save': 'Enregistrer',
    'sos.contact_none': 'Non défini',
    'photo.camera': 'Prendre une photo',
    'photo.gallery': 'Choisir dans la galerie',
    'photo.change': 'Changer la photo',
    'sos.err_name': 'Saisissez le nom de votre contact d’urgence.',
    'sos.err_phone': 'Format international, par ex. +255XXXXXXXXX.',
    'sos.contact_channels': 'Nous lui envoyons WhatsApp et SMS avec votre position exacte.',
    'service.ride': 'Course',
    'service.parcel': 'Colis',
    'service.food': 'Repas',
    'delivery.recipient': 'Destinataire',
    'delivery.recipient_name': 'Son nom',
    'delivery.recipient_phone': 'Son numéro de téléphone',
    'delivery.what': 'Qu’envoyez-vous ?',
    'delivery.what_hint': 'Par exemple : documents, médicaments, déjeuner',
    'delivery.size': 'Taille',
    'delivery.size_small': 'Petit',
    'delivery.size_medium': 'Moyen',
    'delivery.size_large': 'Grand',
    'delivery.note': 'Instructions supplémentaires (facultatif)',
    'delivery.cash': 'Espèces à collecter (facultatif)',
    'delivery.cash_hint': 'Le coursier les récupère auprès du destinataire pour vous.',
    'delivery.code': 'Code de remise',
    'delivery.code_hint': 'Donnez-le au destinataire. Le coursier le demande avant la remise.',
    'delivery.collected': 'J’ai récupéré le colis',
    'delivery.confirm': 'Remettre',
    'delivery.enter_code': 'Saisissez le code du destinataire',
    'delivery.received_by': 'Reçu par (facultatif)',
    'delivery.wrong_code': 'Ce code ne correspond pas.',
    'delivery.delivered': 'Remis',
    'delivery.no_insurance': 'Kwema n’assure pas les objets envoyés.',
    'delivery.err_name': 'Saisissez le nom du destinataire.',
    'delivery.err_what': 'Décrivez ce que vous envoyez.',
    'delivery.failed_title': 'Livraison impossible',
    'category.e_boda': 'Bodaboda électrique',
    'category.e_bajaji': 'Bajaji électrique',
    'category.e_car': 'Voiture électrique',
    'category.electric': 'Électrique',
    'time.minute_one': '{n} minute',
    'time.minute_other': '{n} minutes',
  },
};
